name: Add issues to backlog project

on:
  issues:
    types:
      - labeled

jobs:
  add_to_backlog:
    if: github.event.label.name == 'type:backlog'
    runs-on: ubuntu-latest

    steps:
      - name: Add to GitHub Project (v2)
        uses: actions/add-to-project@v2
        with:
          project-url: https://github.com/users/HiDiHo01/projects/2
          github-token: ${{ secrets.PAT_FOR_FRANK_ENERGIE }}
