name: Claude Code Action Official
permissions:
  contents: read
on:
  issue_comment:
    types: [created]

jobs:
  run-claude:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: read
      pull-requests: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # @v2.20.0
        with:
          egress-policy: block
          allowed-endpoints: "api.github.com:443\ngithub.com:443\npypi.org:443\nfiles.pythonhosted.org:443\nsonarcloud.io:443\nobjects.githubusercontent.com:443\n\nuploads.github.com:443\nupload.pypi.org:443\ntest.pypi.org:443\ncodecov.io:443\nuploader.codecov.io:443"
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # @v7
        with:
          persist-credentials: false
      - uses: anthropics/claude-code-action@e90deca47693f9457b72f2b53c17d7c445a87342
        with:
          trigger_phrase: "@claude"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
