name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # @v2.20.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            raw.githubusercontent.com:443
            github.com:443
            pypi.org:443
            files.pythonhosted.org:443
            sonarcloud.io:443
            objects.githubusercontent.com:443
            uploads.github.com:443
            upload.pypi.org:443
            test.pypi.org:443
            codecov.io:443
            uploader.codecov.io:443
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # @v7

        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # @v6
        with:
          node-version: 22
          cache: npm
          registry-url: https://npm.pkg.github.com
          scope: '@HiDiHo'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: build

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # @v2.20.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            raw.githubusercontent.com:443
            github.com:443
            pypi.org:443
            files.pythonhosted.org:443
            sonarcloud.io:443
            objects.githubusercontent.com:443
            uploads.github.com:443
            upload.pypi.org:443
            test.pypi.org:443
            codecov.io:443
            uploader.codecov.io:443
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # @v5
