name: Link Check

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  link-check:
    permissions:
      contents: read
    name: Validate Documentation Links
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # @v2.20.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            raw.githubusercontent.com:443
            release-assets.githubusercontent.com:443
            github.com:443
            pypi.org:443
            files.pythonhosted.org:443
            sonarcloud.io:443
            objects.githubusercontent.com:443
            uploads.github.com:443
            upload.pypi.org:443
            test.pypi.org:443
            codecov.io:443
            uploader.codecov.io:443
            www.home-assistant.io:443
            www.buymeacoffee.com:443
            docs.python.org:443
            peps.python.org:443
            www.paypal.me:443
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # @v7

        with:
          persist-credentials: false
      - name: Run Lychee
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # @v2
        with:
          fail: true
          args: >-
            --verbose
            --no-progress
            --accept 200,403,429
            --root-dir .
            --exclude-file .lycheeignore .
            README.md
            docs/**/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
