name: Link Check

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  link-check:
    permissions:
      contents: read
    name: Validate Documentation Links
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # @v2.8.1
        with:
          egress-policy: block
          allowed-endpoints: "api.github.com:443\ngithub.com:443\npypi.org:443\nfiles.pythonhosted.org:443\nsonarcloud.io:443\nobjects.githubusercontent.com:443\n\nuploads.github.com:443\nupload.pypi.org:443\ntest.pypi.org:443\ncodecov.io:443\nuploader.codecov.io:443"
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # @v7

      - name: Run Lychee
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # @v2
        with:
          fail: true
          args: >-
            --verbose
            --no-progress
            --accept 200,403,429
            --root-dir .
            --exclude-file .lycheeignore .
            README.md
            docs/**/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
