# Combine files and upload it as zip to the release
# Original file from https://github.com/hacs/integration/blob/main/.github/workflows/release.yml

name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release_zip_file:
    permissions:
      contents: write
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # @v2.20.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            raw.githubusercontent.com:443
            github.com:443
            pypi.org:443
            files.pythonhosted.org:443
            sonarcloud.io:443
            objects.githubusercontent.com:443
            uploads.github.com:443
            upload.pypi.org:443
            test.pypi.org:443
            codecov.io:443
            uploader.codecov.io:443
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # @v7

        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # @v6
        with:
          python-version: "3.13"

      - name: "Set version number"
        run: |
          python3 ${{ github.workspace }}/.github/helpers/update_manifest.py --version ${GITHUB_REF##*/}

      - name: Combine ZIP
        run: |
          cd ${{ github.workspace }}/custom_components/frank_energie
          zip frank_energie.zip -r ./

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ${{ github.workspace }}/custom_components/frank_energie/frank_energie.zip
