# Combine files and upload it as zip to the release
# Original file from https://github.com/hacs/integration/blob/main/.github/workflows/release.yml

name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release_zip_file:
    permissions:
      contents: read
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # @v2.8.1
        with:
          egress-policy: block
          allowed-endpoints: "api.github.com:443\ngithub.com:443\npypi.org:443\nfiles.pythonhosted.org:443\nsonarcloud.io:443\nobjects.githubusercontent.com:443\n\nuploads.github.com:443\nupload.pypi.org:443\ntest.pypi.org:443\ncodecov.io:443\nuploader.codecov.io:443"
      - name: Check out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # @v7

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # @v6
        with:
          python-version: "3.13"

      - name: "Set version number"
        run: |
          python3 ${{ github.workspace }}/.github/helpers/update_manifest.py --version ${GITHUB_REF##*/}

      - name: Combine ZIP
        run: |
          cd ${{ github.workspace }}/custom_components/frank_energie
          zip frank_energie.zip -r ./

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@74c3d60f5a28f358ccf241a00c9021ea16f0569f # v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/custom_components/frank_energie/frank_energie.zip
          asset_name: frank_energie.zip
          asset_content_type: application/zip
