name: Ruff

on:
  pull_request:
    paths:
      - "custom_components/**/*.py"
      - "pyproject.toml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    permissions:
      contents: read
    name: Lint & format check
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # @v2.20.0
        with:
          egress-policy: block
          allowed-endpoints: "api.github.com:443\ngithub.com:443\npypi.org:443\nfiles.pythonhosted.org:443\nsonarcloud.io:443\nobjects.githubusercontent.com:443\n\nuploads.github.com:443\nupload.pypi.org:443\ntest.pypi.org:443\ncodecov.io:443\nuploader.codecov.io:443"
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # @v7

        with:
          persist-credentials: false
      - name: Ruff lint
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
        with:
          args: "check custom_components"

      - name: Ruff format check
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
        with:
          args: "format --check custom_components"
